from http.server import BaseHTTPRequestHandler, HTTPServer
import html
import json

from risk_engine import analyze_transactions
from gemini_service import generate_investigation_report

HOST = "0.0.0.0"
PORT = 8000
TRANSACTION_FILE = "data/transactions.csv"


def build_page(evidence=None, report=None, error=None):

    evidence_html = ""

    if evidence:
        findings_html = ""

        for finding in evidence["findings"]:
            ids = ", ".join(finding["transaction_ids"])

            findings_html += f"""
            <div class="finding">
                <div class="finding-header">
                    <strong>{html.escape(finding["rule"])}</strong>
                    <span>{html.escape(ids)}</span>
                </div>
                <p>{html.escape(finding["reason"])}</p>
            </div>
            """

        evidence_html = f"""
        <section class="evidence">
            <h2>Deterministic Risk Findings</h2>

            <div class="stats">
                <div class="stat">
                    <strong>{evidence["transaction_count"]}</strong>
                    <span>Transactions Analyzed</span>
                </div>

                <div class="stat">
                    <strong>{len(evidence["findings"])}</strong>
                    <span>Risk Findings</span>
                </div>

                <div class="stat">
                    <strong>{html.escape(evidence["investigation_priority"])}</strong>
                    <span>Priority</span>
                </div>
            </div>

            {findings_html}

            <div class="notice">
                <strong>Important:</strong>
                These findings are generated by deterministic Python rules.
                Gemini receives this evidence only to explain and format
                the investigation report.
            </div>
        </section>
        """

    report_html = ""

    if report:
        report_html = f"""
        <section class="report">
            <h2>Gemini Investigation Report</h2>

            <pre>{html.escape(report)}</pre>
        </section>
        """

    error_html = ""

    if error:
        error_html = f"""
        <section class="error">
            <strong>Error:</strong>
            {html.escape(str(error))}
        </section>
        """

    return f"""
    <!DOCTYPE html>

    <html>

    <head>

        <meta charset="UTF-8">

        <meta name="viewport"
              content="width=device-width, initial-scale=1.0">

        <title>RiskLens</title>

        <style>

            * {{
                box-sizing: border-box;
            }}

            body {{
                margin: 0;
                font-family: Arial, sans-serif;
                background: #f4f6f8;
                color: #1f2937;
            }}

            .container {{
                max-width: 1100px;
                margin: 0 auto;
                padding: 40px 20px;
            }}

            .header {{
                background: white;
                padding: 30px;
                border-radius: 14px;
                margin-bottom: 25px;
                box-shadow: 0 2px 8px rgba(0,0,0,0.08);
            }}

            h1 {{
                margin: 0 0 8px;
                font-size: 34px;
            }}

            h2 {{
                margin-top: 0;
            }}

            .subtitle {{
                color: #6b7280;
                font-size: 18px;
                margin-bottom: 20px;
            }}

            button {{
                background: #111827;
                color: white;
                border: none;
                padding: 13px 24px;
                border-radius: 8px;
                font-size: 16px;
                cursor: pointer;
            }}

            button:hover {{
                opacity: 0.9;
            }}

            section {{
                background: white;
                padding: 28px;
                border-radius: 14px;
                margin-bottom: 25px;
                box-shadow: 0 2px 8px rgba(0,0,0,0.08);
            }}

            .stats {{
                display: flex;
                gap: 15px;
                margin: 20px 0;
                flex-wrap: wrap;
            }}

            .stat {{
                flex: 1;
                min-width: 180px;
                background: #f3f4f6;
                padding: 18px;
                border-radius: 10px;
            }}

            .stat strong {{
                display: block;
                font-size: 25px;
                margin-bottom: 5px;
            }}

            .stat span {{
                color: #6b7280;
                font-size: 14px;
            }}

            .finding {{
                border: 1px solid #e5e7eb;
                border-radius: 10px;
                padding: 16px;
                margin-bottom: 12px;
            }}

            .finding-header {{
                display: flex;
                justify-content: space-between;
                gap: 15px;
                flex-wrap: wrap;
            }}

            .finding-header span {{
                font-family: monospace;
                font-size: 13px;
                color: #6b7280;
            }}

            .finding p {{
                margin-bottom: 0;
                line-height: 1.5;
            }}

            .notice {{
                margin-top: 20px;
                padding: 16px;
                background: #f3f4f6;
                border-radius: 10px;
                line-height: 1.5;
            }}

            .report pre {{
                white-space: pre-wrap;
                word-wrap: break-word;
                line-height: 1.6;
                font-family: Arial, sans-serif;
            }}

            .architecture code {{
                display: block;
                background: #f3f4f6;
                padding: 18px;
                border-radius: 10px;
                line-height: 2;
                font-family: monospace;
            }}

            .error {{
                background: #fee2e2;
                color: #991b1b;
            }}

            .footer-note {{
                color: #6b7280;
                font-size: 14px;
                text-align: center;
                margin-top: 30px;
            }}

        </style>

    </head>

    <body>

        <div class="container">

            <div class="header">

                <h1>RiskLens</h1>

                <div class="subtitle">
                    Transaction Risk Investigation Assistant
                </div>

                <p>
                    Analyze customer transaction history using
                    deterministic risk rules and grounded Gemini
                    investigation reports.
                </p>

                <form method="POST">

                    <button type="submit">
                        Analyze Transactions
                    </button>

                </form>

            </div>

            {error_html}

            {evidence_html}

            {report_html}

            <section class="architecture">

                <h2>How RiskLens Works</h2>

                <code>
                    Transaction History<br>
                    ↓<br>
                    Python Deterministic Risk Engine<br>
                    ↓<br>
                    Evidence & Risk Findings<br>
                    ↓<br>
                    Grounded Gemini Explanation<br>
                    ↓<br>
                    Human Investigator
                </code>

            </section>

            <div class="footer-note">
                RiskLens flags transactions for investigation.
                It does not determine or declare fraud.
            </div>

        </div>

    </body>

    </html>
    """


class RiskLensHandler(BaseHTTPRequestHandler):

    def send_html(self, content):

        encoded_content = content.encode("utf-8")

        self.send_response(200)

        self.send_header(
            "Content-Type",
            "text/html; charset=utf-8"
        )

        self.send_header(
            "Content-Length",
            str(len(encoded_content))
        )

        self.end_headers()

        self.wfile.write(encoded_content)

    def do_GET(self):

        page = build_page()

        self.send_html(page)

    def do_POST(self):

        try:

            evidence = analyze_transactions(
                TRANSACTION_FILE
            )

            report = generate_investigation_report(
                evidence
            )

            page = build_page(
                evidence=evidence,
                report=report
            )

            self.send_html(page)

        except Exception as error:

            page = build_page(
                error=error
            )

            self.send_html(page)


def start_server():

    server = HTTPServer(
        (HOST, PORT),
        RiskLensHandler
    )

    print("=" * 60)
    print("RiskLens Transaction Risk Investigation Assistant")
    print("=" * 60)
    print()
    print(f"Server running at: http://localhost:{PORT}")
    print()
    print("Press Ctrl+C to stop the server.")
    print()

    server.serve_forever()


if __name__ == "__main__":
    start_server()